server:
  port: 8085
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro_chat_room?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '@Wwindows8'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 180000
      auto-commit: true
      pool-name: CloudHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1

mybatis:
  mapper-locations: classpath:com/micro/cloud/mapper/xml/*.xml
  type-aliases-package: com.micro.cloud.entity

thrift:
  user:
    port: 8086