server:
  port: 8085
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro_chat_room?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT-8
    username: root
    password: '@Wwindows8'
#    password: 'zxbqq'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 180000
      auto-commit: true
      pool-name: CloudHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      file-size-threshold: 2KB
      max-request-size: 30MB

# Mybatis
mybatis:
  mapper-locations: classpath:com/micro/im/mapper/xml/*.xml
  type-aliases-package: com.micro.im.entity

# Redis 缓存配置
cache:
  timeout: 60
  cacheExpirations:
    myControlledCache: 180

# 邮件配置
mail:
  smtp:
    #服务器主机名
    host: smtp.gmail.com
    #你的邮箱地址
    username: thersayibui822@gmail.com
    #授权码
    port: 587
    password: cbfbvobwzhnveokg
    #编码格式
    defaultEncoding: utf-8
    #是否进行用户名密码校验
    auth: true
    #设置超时时间
    timeout: 20000